name: 📖 TOC Generator
on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - '.github/workflows/toc.yml'
  pull_request:
    branches: [main]
    paths:
      - 'README.md'
      - '.github/workflows/toc.yml'
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "## Table of Contents"
          CUSTOM_MODE: true
